//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id_Pedidos { get; set; }
        public string Nombre_De_Producto { get; set; }
        public string Nombre_Del_Cliente { get; set; }
        public string Articulo { get; set; }
        public string Talle_Del_Producto { get; set; }
        public string Fecha_Del_Pedido { get; set; }
    }
}
